### ISSUE TITLE
Change the value of AuthnCacheContext? 

### ISSUE THREAD

**Issue by ghost** [tchabaud/dockerfiles#11]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by t-chab** [comment]
If you want to customize Apache httpd configuration, you can mount a custom configuration directory as [a docker volume](https://docs.docker.com/storage/volumes/) using -v flag :

```bash
docker run -v /path/to/your/custom/httpd/conf:/etc/apache2 tchabaud/httpd
```
