### ISSUE TITLE
Question about ServerName and ServerAdmin?

### ISSUE THREAD

**Issue by odunybrad** [tchabaud/dockerfiles#12]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerName` is set to `www.example.com:443` in `etc/apache2/conf.d/ssl.conf` and `ServerAdmin` is set to `you@example.com` in `/etc/apache2/httpd.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerName` : "For optimal reliability and predictability, you should specify an explicit hostname and port using the ServerName directive."
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerName` and `ServerAdmin` to identify yourself?

**Comment by t-chab** [comment]
Please see https://github.com/tchabaud/dockerfiles/issues/11#issuecomment-674515941 to customize httpd config.
