### ISSUE TITLE
Why not using alpine packages instead of building from source? 

### ISSUE THREAD

**Issue by garret** [tchabaud/dockerfiles#15]
I was wondering if there is a particular reason why you build from source amule (and also some other dependencies). 
Why not using the version already packaged in alpine linux? 

https://pkgs.alpinelinux.org/packages?name=amule&branch=edge

**Comment by t-chab** [comment]
@garret : Thanks for your interest in this humble project. It's because I prefer to depend on stable Alpine images at the moment.
