### ISSUE TITLE
What is the default entry password plz?

### ISSUE THREAD

**Issue by Gamersmile** [tchabaud/dockerfiles#16]
Tks for composing the docker image. Yet I was not able to enter the web UI after installation on a Synology NAS device.
It simply prompts me with a logon window, awaits my password input.

Being a novice Synology user without Linux/Unix exposure, I cannot find the config file for aMule in the docker.

Is there a default password for this? Tks for any help in advance.

Below is my defalt setting:
![aMule Synology docker setting](https://user-images.githubusercontent.com/60468058/106982742-9ad45600-679f-11eb-9444-a99a7e3b0a21.png)

**Comment by t-chab** [comment]
@Gamersmile : sorry but  there is not default password. You can specify the password you want by using the WEBUI_PWD for web interface, or GUI_PWD if you use the GUI. If you don't specify a password, a random one will be generated at container startup. You can get it by using the following command to display logs : 

```bash
docker logs -f [YOUR_CONTAINER_NAME]
```
