### ISSUE TITLE
Update Amule version to 2.3.3

### ISSUE THREAD

**Issue by ngosang** [tchabaud/dockerfiles#17]
Amule 2.3.3 is released after 4 years.

https://github.com/amule-project/amule/releases/tag/2.3.3

**Comment by ngosang** [comment]
@synopsis8  Could you update your ARM32 fork too?

https://github.com/synopsis8/dockerfiles/blob/master/amule/Dockerfile

**Comment by synopsis8** [comment]
> @synopsis8 Could you update your ARM32 fork too?
> 
> https://github.com/synopsis8/dockerfiles/blob/master/amule/Dockerfile

Hello, I've updated the Dockerfile, not yet the docker image. You can still build it locally

**Comment by ngosang** [comment]
I released my own image with several improvements and architectures.
https://github.com/ngosang/docker-amule
