### ISSUE TITLE
amule: Allow USERID and GROUPID instead of forcing 5000

### ISSUE THREAD

**Issue by alesnav** [tchabaud/dockerfiles#2]
Hello,

I would like to use your dockerfile for amule, but I has to change the user ID and group ID to another number to be able to write on my NAS using my actual configuration. At this moment, your docker image force amule process to run under UID 5000 and GID 5000.

For example, [LinuxServer/nzbget](https://hub.docker.com/r/linuxserver/nzbget/) does allow it by using environment variables for `PUID` and `PGID`, which means "Process User/Group ID".

Is it possible to implement this kind of configuration in your repo?

Thanks,
Best regards

**Comment by t-chab** [comment]
Hello, and thanks for you feedback.

I've done slight modifications to allow uid / group id customization through environment variables, as you mentioned.

Can you please check if it's OK for you ?

**Comment by alesnav** [comment]
Thank you so much! Sorry, I was a bit busy today, will try it tomorrow :)

**Comment by alesnav** [comment]
@tchabaud it works like a charm! :)

How should I change the amuleweb password? Can you add it to the readme file?

Thanks!

**Comment by t-chab** [comment]
I just have commited an update to allow passwords customizations via environment variables.

I'll update the doc after I could have tested these modifications.

**Comment by t-chab** [comment]
Hello @alesnav 

Tests are successful, documentation updated.

Enjoy :smile:

**Comment by alesnav** [comment]
Yep, it works fine! Thank you :)
