### ISSUE TITLE
aMule: Web UI password

### ISSUE THREAD

**Issue by lukezona** [tchabaud/dockerfiles#3]
Hi, I've tried to move a current installation to a docker container.

It seems to work everything except for the web UI password.
I've passed it as an environment variable as described but when I write it and then try to login it doesn't login.

In the logs I can't see anything useful.

> addgroup: group 'amule' in use
> adduser: user 'amule' in use
> /home/amule/.aMule/amule.conf file found. Using existing configuration.
> /home/amule/.aMule/remote.conf file found. Using existing configuration.
>  2018-04-05 17:39:29: Logging to stdout enabled
>  2018-04-05 17:39:29: Initialising aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)
>  2018-04-05 17:39:29: Checking if there is an instance already running...
>  2018-04-05 17:39:29: No other instances are running.
> !2018-04-05 17:39:29: ERROR: Error accessing directory. Permissions on the temp directory too strict!
> !2018-04-05 17:39:29: aMule cannot proceed. To fix this, you must set read/write/exec
> !2018-04-05 17:39:29: permissions for the folder '/temp'
> !2018-04-05 17:39:29: Attempting to use default directory at location 
> !2018-04-05 17:39:29: '/home/amule/.aMule/Temp'.
>  2018-04-05 17:39:29: Creditfile loaded, 2386 clients are known
>  2018-04-05 17:39:29: *** TCP socket (ECServer) listening on 0.0.0.0:4712
>  2018-04-05 17:39:29: Created Server UDP-Socket at port 4665
>  2018-04-05 17:39:29: ListenSocket: Ok.
>  2018-04-05 17:39:29: Created Client UDP-Socket at port 4672
>  2018-04-05 17:39:29: Loading server.met file: /home/amule/.aMule/server.met
> !2018-04-05 17:39:29: 20 servers in server.met found
>  2018-04-05 17:39:29: Loading temp files from /home/amule/.aMule/Temp.
>  2018-04-05 17:39:29: All PartFiles Loaded.
>  2018-04-05 17:39:29: No part files found
>  2018-04-05 17:39:29: No shareable files found in directory: /incoming
>  2018-04-05 17:39:29: Found 0 known shared files
> !2018-04-05 17:39:30: web server running on pid 31
>  2018-04-05 17:39:30: amuled: OnInit - starting timer
>  2018-04-05 17:39:30: Loading IP filters 'ipfilter.dat' and 'ipfilter_static.dat'.
>  2018-04-05 17:39:30: Loaded 0 IP-ranges from '/home/amule/.aMule/ipfilter.dat'.
>  2018-04-05 17:39:30: Loaded 0 IP-ranges from '/home/amule/.aMule/ipfilter_static.dat'.
>  2018-04-05 17:39:30: IP filter is ready
> !2018-04-05 17:39:30: Connecting
>  2018-04-05 17:39:30: Connecting to eDonkey Server No2 (176.103.56.135 - 176.103.56.135:2442) using protocol obfuscation.
>  2018-04-05 17:39:30: Read 166 Kad contacts
> !2018-04-05 17:39:30: Kad started.
>  2018-04-05 17:39:30: New external connection accepted
> !2018-04-05 17:39:30: Kad stopped.
> !2018-04-05 17:39:30: Connected to Kad (firewalled)
>  2018-04-05 17:39:30: Connecting client: aMuleweb 2.3.2
>  2018-04-05 17:39:30: Access granted.
>  2018-04-05 17:39:30: Connected to eDonkey Server No2 (176.103.56.135:2442)
>  2018-04-05 17:39:30: Connecting to eMule Security (80.208.228.241 - 80.208.228.241:8369) using protocol obfuscation.
>  2018-04-05 17:39:30: Connected to eMule Security (80.208.228.241:8369)
> !2018-04-05 17:39:31: Connection established on: eMule Security
> !2018-04-05 17:39:31: Connected to eMule Security with HighID
>  2018-04-05 17:39:31: New clientid is 3306683284
>  2018-04-05 17:39:31: ServerMessage: server version 17.15 (lugdunum)
>  2018-04-05 17:39:31: ServerMessage: Welcome to eMule Security! <> www.emule-security.org
>  2018-04-05 17:39:31: ServerMessage: Download Safe Serverlist > http://www.emule-security.org/serverlist/
>  2018-04-05 17:39:31: ServerMessage: IP-filter > http://www.emule-security.org/e107_plugins/faq/faq.php?0.cat.2.1
>  2018-04-05 17:39:31: ServerMessage: nodes.dat > http://www.emule-security.org/e107_plugins/faq/faq.php?0.cat.6.6

Any guess on what could be wrong?

**Comment by t-chab** [comment]
Hi,

Sorry if the doc is unclear, but _GUI_PWD_ / _WEBUI_PWD_ environments variables are only used to initiate passwords on a fresh install.

If you have an existing amule configuration, you should use the original password you've set.

**Comment by lukezona** [comment]
The problem is that the password wasn't set before (the webserver wasn't enabled).

So I don't know where I should put it in the .conf file and if I have to write it somewhere after I have set to 1 the "Enabled" field

> [WebServer]
> Enabled=1
> Password=
> PasswordLow=
Port=4711
WebUPnPTCPPort=50001
UPnPWebServerEnabled=0
UseGzip=1
UseLowRightsUser=0
PageRefreshTime=120
Template=default
Path=amuleweb

**Comment by lukezona** [comment]
Nevermind, I created an encrypted version of my password and put it in the "Password" field and it works.

**Comment by t-chab** [comment]
I'm glad you solved your problem. I'll update the doc to be more specific about password environment variables usage.

**Comment by kettly1260** [comment]
> Nevermind, I created an encrypted version of my password and put it in the "Password" field and it works.

@lukezona @tchabaud 
How is your problem solved? I did not configure a password in the environment, modified the two passwords in amule.conf and remote.conf to the corresponding MD5, but the file does not take effect. After restarting the container, it changed back to the original MD5 and could not log in.
