### ISSUE TITLE
aMule broken with latest commit

### ISSUE THREAD

**Issue by romancin** [tchabaud/dockerfiles#5]
Hello! With the latest image amule has been broken for me:
```
/home/amule/amule.sh: set: line 7: illegal option -E
/home/amule/amule.sh: set: line 7: illegal option -E
```
If I edit the file amule.sh on the overlay filesystem and comment line 7, another error appears:
```
sudo: unknown user: 5000
sudo: unable to initialize policy plugin
```
Do you know what can be wrong? Thank you!

**Comment by t-chab** [comment]
Hello,

Thanks for the report. Should be fixed by 02448b6bd4035aa44fd866a7a5d1c75add7b053b

I'll wait your confirmation before closing the issue.

**Comment by romancin** [comment]
Wow! So fast! Thank you!

Now different error:
docker logs -f amule

Directory /incoming does not exists. Creating ...
Directory /temp does not exists. Creating ...
/home/amule/amule.sh: line 42: GUI_PWD: unbound variable
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use
addgroup: group 'amule' in use

**Comment by t-chab** [comment]
Sorry, I made two commits / pushs in a row and the last one should not have been taken with the Docker hub build. Just to be sure, I've made another small commit / push.

Could you please retry with the last image available ?

**Comment by romancin** [comment]
Working. Thank you very much!
